version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - tramoya-network
    restart: unless-stopped

  gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=tramoya
      - MINIO_USE_SSL=false
      - REDIS_URL=redis://redis:6379
      - SERVICE_TYPE=gateway
    depends_on:
      - minio
      - redis
    networks:
      - tramoya-network
    restart: unless-stopped

  runner:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=tramoya
      - MINIO_USE_SSL=false
      - REDIS_URL=redis://redis:6379
      - SERVICE_TYPE=runner
    depends_on:
      - minio
      - redis
    networks:
      - tramoya-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - tramoya-network
    restart: unless-stopped

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    networks:
      - tramoya-network
    restart: unless-stopped

  # Create the initial bucket
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing myminio/tramoya;
      /usr/bin/mc anonymous set public myminio/tramoya;
      exit 0;
      "
    networks:
      - tramoya-network

networks:
  tramoya-network:
    driver: bridge

volumes:
  minio-data:
    driver: local
  redis-data:
    driver: local